### ISSUE TITLE
check-ses-statistics.rb with no credentials parameters

### ISSUE THREAD

**Issue by guannais** [sensu-plugins/sensu-plugins-aws#225]
It´s possible to use check-ses-statistics.rb as check-rds.rb with the same credentials parameters? I have review help output and code but I cann´t find the way to specify credentials.

Regards,

**Comment by majormoses** [comment]
@guannais there are two options, either use IAM or use the ENV var that aws client automatically uses. We are in the process of removing passing aws api keys on the CLI because of the security implications and opting for the native authentication methods available. I would suggest looking into doing this for all checks you are using as we will eventually remove the capability to set this via a param at some point from all the checks. Right now some support old insecure methods others only support secure delivery methods.

**Comment by guannais** [comment]
@majormoses thanks for your explain. I´m really new using Ruby. How can I use different ENV vars to diffent AWS accounts? I know who to use CLI credentials 
{code}
check-rds-events.rb -r eu-central-1 -a ***************** -k *****************
{code}

Can I set this vars in check json sensu file?

Regards,

**Comment by majormoses** [comment]
Well one way to do it (I don't recommend for anything, for local dev just export them to the ENV) is to do something like this:
`AWS_ACCESS_KEY_ID=MY_ACCESS_KEY AWS_SECRET_ACCESS_KEY=MY_SECRET_KEY check-rds-events.rb -r eu-central-1`

As this really has the same issue with being accessible via ps I'd opt for something more like writing each set of credentials to a file and then do something like this:
`source $PATH_TO_SPECIFIC_REGION_CREDS check-rds-events.rb -r eu-central-1`

You could also combine the above with using sensu token substitution so you know which file to source: https://sensuapp.org/docs/latest/reference/checks.html#check-token-substitution 

Other options are:
1. Run one sensu server per aws region (I do this personally for many reasons including security, scale, having each env build exactly like every other env, etc), you can always have uchiwa display it in one place if that is desired. This also is preferable since you can rely solely on IAM and not require any keys passed except local development.
1. Allow the same user access across multiple accounts (not recommended as this violates the principle of least privilege)

**Comment by guannais** [comment]
Thank you very much for your help. I have just began to use token substitution and I discover a new world! 👍  👍 

Thanks again!
