### ISSUE TITLE
metrics-elasticache.rb

### ISSUE THREAD

**Issue by NeckBeardPrince** [sensu-plugins/sensu-plugins-aws#32]
Check failed to run: undefined method `downcase' for nil:NilClass, ["/var/lib/gems/1.9.1/gems/sensu-plugins-aws-1.2.0/bin/metrics-elasticache.rb:95:in `run'", "/var/lib/gems/1.9.1/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

**Comment by NeckBeardPrince** [comment]
Still getting this.. any info?

Check failed to run: undefined method `downcase' for nil:NilClass, ["/var/lib/gems/1.9.1/gems/sensu-plugins-aws-1.2.0/bin/metrics-elasticache.rb:95:in `run'", "/var/lib/gems/1.9.1/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

**Comment by eheydrick** [comment]
@NeckBeardPrince, looks like the problem is `config[:elasticachename]` and `config[:metric]` are not defined by options yet they are referenced throughout the script. I don't think metric needs to be an option since they are defined in the hash. `config[: elasticachename]` should probably be `config[:cacheclusterid]`. I don't have an elasticache cluster handy but would happily take a PR.

**Comment by eheydrick** [comment]
I fixed the default scheme and the plugin now returns metrics. It'll be included in the next release which will be out soon.
